---
title: 'Hazard Ratios for BMI as continuous variable'
output:
  html_document:
    code_folding: hide
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 4
    toc_float: yes
editor_options:
  chunk_output_type: console
---

```{r options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, comment = FALSE, 
                      cache.lazy = FALSE)
options(scipen=999)
options(knitr.kable.NA = '')
```

```{r package, include=FALSE}
# packbmi.all_times -----
library(kableExtra)
library(dplyr)
library(tidyr)
library(ggplot2)
library(rms)
library(stargazer)
library(ggstance)
library(stringr)
library(knitr)
```

```{r data, include=FALSE}

# complete case data
# adding age categories
# merging obesity classes into one

load("1 data prep/working data.RData")

covid.data<-covid.data%>%
  filter(!is.na(bmi.all_time_gr))%>%
  mutate(age_gr.b= ifelse(age<=59, "Aged 18 to 59", 
                          ifelse(age<=79, "Aged 60 to 79", 
                                 "Aged 80 or above" ))) %>% 
  mutate(age_gr.b = factor(age_gr.b, levels = c("Aged 18 to 59", "Aged 60 to 79","Aged 80 or above"))) %>%
  filter(!is.na(smoke.all_time))%>%
  mutate(smoke.all_time=factor(smoke.all_time))%>%
  mutate(smoke.all_time=relevel(smoke.all_time, "Never smoker"))%>%
  filter(!is.na(medea))%>%
  mutate(medea=relevel(medea, "U1"))%>%
  droplevels()
levels(covid.data$bmi.all_time_gr)=list("normal or underweight"="normal or underweight",
                                        "overweight" ="overweight",
                                        "obese"=c("obese class I", "obese class II", "obese class III"))

r<-r %>%
  filter(!is.na(bmi.all_time_gr))%>%
  mutate(age_gr.b= ifelse(age<=59, "Aged 18 to 59", 
                          ifelse(age<=79, "Aged 60 to 79", 
                                 "Aged 80 or above" ))) %>% 
  mutate(age_gr.b = factor(age_gr.b, levels = c("Aged 18 to 59", "Aged 60 to 79","Aged 80 or above"))) %>%
  filter(!is.na(smoke.all_time))%>%
  mutate(smoke.all_time=factor(smoke.all_time))%>%
  mutate(smoke.all_time=relevel(smoke.all_time, "Never smoker"))%>%
  filter(!is.na(medea))%>%
  mutate(medea=relevel(medea, "U1"))%>%
  droplevels()
levels(r$bmi.all_time_gr)=list("normal or underweight"="normal or underweight",
                               "overweight" ="overweight",
                               "obese"=c("obese class I", "obese class II", "obese class III"))

r.healthy.diagnosis<-r.healthy.diagnosis %>%
  filter(!is.na(bmi.all_time_gr))%>%
  mutate(age_gr.b= ifelse(age<=59, "Aged 18 to 59", 
                          ifelse(age<=79, "Aged 60 to 79", 
                                 "Aged 80 or above" ))) %>% 
  mutate(age_gr.b = factor(age_gr.b, levels = c("Aged 18 to 59", "Aged 60 to 79","Aged 80 or above"))) %>%
  filter(!is.na(smoke.all_time))%>%
  mutate(smoke.all_time=factor(smoke.all_time))%>%
  mutate(smoke.all_time=relevel(smoke.all_time, "Never smoker"))%>%
  filter(!is.na(medea))%>%
  mutate(medea=relevel(medea, "U1"))%>%
  droplevels()
levels(r.healthy.diagnosis$bmi.all_time_gr)=list("normal or underweight"="normal or underweight",
                                                 "overweight" ="overweight",
                                                 "obese"=c("obese class I", "obese class II", "obese class III"))

r.healthy.hospitalised<-r.healthy.hospitalised %>% 
  filter(!is.na(bmi.all_time_gr))%>%
  mutate(age_gr.b= ifelse(age<=59, "Aged 18 to 59", 
                          ifelse(age<=79, "Aged 60 to 79", 
                                 "Aged 80 or above" ))) %>% 
  mutate(age_gr.b = factor(age_gr.b, levels = c("Aged 18 to 59", "Aged 60 to 79","Aged 80 or above"))) %>%
  filter(!is.na(smoke.all_time))%>%
  mutate(smoke.all_time=factor(smoke.all_time))%>%
  mutate(smoke.all_time=relevel(smoke.all_time, "Never smoker"))%>%
  filter(!is.na(medea))%>%
  mutate(medea=relevel(medea, "U1"))%>%
  droplevels()
levels(r.healthy.hospitalised$bmi.all_time_gr)=list("normal or underweight"="normal or underweight",
                                                    "overweight" ="overweight",
                                                    "obese"=c("obese class I", "obese class II", "obese class III"))

r.healthy.death<-r.healthy.death %>% 
  filter(!is.na(bmi.all_time_gr))%>%
  mutate(age_gr.b= ifelse(age<=59, "Aged 18 to 59", 
                          ifelse(age<=79, "Aged 60 to 79", 
                                 "Aged 80 or above" ))) %>% 
  mutate(age_gr.b = factor(age_gr.b, levels = c("Aged 18 to 59", "Aged 60 to 79","Aged 80 or above"))) %>%
  filter(!is.na(smoke.all_time))%>%
  mutate(smoke.all_time=factor(smoke.all_time))%>%
  mutate(smoke.all_time=relevel(smoke.all_time, "Never smoker"))%>%
  filter(!is.na(medea))%>%
  mutate(medea=relevel(medea, "U1"))%>%
  droplevels()
levels(r.healthy.death$bmi.all_time_gr)=list("normal or underweight"="normal or underweight",
                                             "overweight" ="overweight",
                                             "obese"=c("obese class I", "obese class II", "obese class III"))

r.diagnosis.hospitalised<-r.diagnosis.hospitalised %>% 
  filter(!is.na(bmi.all_time_gr))%>%
  mutate(age_gr.b= ifelse(age<=59, "Aged 18 to 59", 
                          ifelse(age<=79, "Aged 60 to 79", 
                                 "Aged 80 or above" ))) %>% 
  mutate(age_gr.b = factor(age_gr.b, levels = c("Aged 18 to 59", "Aged 60 to 79","Aged 80 or above"))) %>%
  filter(!is.na(smoke.all_time))%>%
  mutate(smoke.all_time=factor(smoke.all_time))%>%
  mutate(smoke.all_time=relevel(smoke.all_time, "Never smoker"))%>%
  filter(!is.na(medea))%>%
  mutate(medea=relevel(medea, "U1"))%>%
  droplevels()
levels(r.diagnosis.hospitalised$bmi.all_time_gr)=list("normal or underweight"="normal or underweight",
                                                      "overweight" ="overweight",
                                                      "obese"=c("obese class I", "obese class II", "obese class III"))

r.diagnosis.death<-r.diagnosis.death %>% 
  filter(!is.na(bmi.all_time_gr))%>%
  mutate(age_gr.b= ifelse(age<=59, "Aged 18 to 59", 
                          ifelse(age<=79, "Aged 60 to 79", 
                                 "Aged 80 or above" ))) %>% 
  mutate(age_gr.b = factor(age_gr.b, levels = c("Aged 18 to 59", "Aged 60 to 79","Aged 80 or above"))) %>%
  filter(!is.na(smoke.all_time))%>%
  mutate(smoke.all_time=factor(smoke.all_time))%>%
  mutate(smoke.all_time=relevel(smoke.all_time, "Never smoker"))%>%
  filter(!is.na(medea))%>%
  mutate(medea=relevel(medea, "U1"))%>%
  droplevels()
levels(r.diagnosis.death$bmi.all_time_gr)=list("normal or underweight"="normal or underweight",
                                               "overweight" ="overweight",
                                               "obese"=c("obese class I", "obese class II", "obese class III"))

r.hospitalised.death<-r.hospitalised.death %>% 
  filter(!is.na(bmi.all_time_gr))%>%
  mutate(age_gr.b= ifelse(age<=59, "Aged 18 to 59", 
                          ifelse(age<=79, "Aged 60 to 79", 
                                 "Aged 80 or above" ))) %>% 
  mutate(age_gr.b = factor(age_gr.b, levels = c("Aged 18 to 59", "Aged 60 to 79","Aged 80 or above"))) %>%
  filter(!is.na(smoke.all_time))%>%
  mutate(smoke.all_time=factor(smoke.all_time))%>%
  mutate(smoke.all_time=relevel(smoke.all_time, "Never smoker"))%>%
  filter(!is.na(medea))%>%
  mutate(medea=relevel(medea, "U1"))%>%
  droplevels()
levels(r.hospitalised.death$bmi.all_time_gr)=list("normal or underweight"="normal or underweight",
                                                  "overweight" ="overweight",
                                                  "obese"=c("obese class I", "obese class II", "obese class III"))
```

```{r functions}
## Functions

# For printing numbers
nice.num<-function(x){
  prettyNum(x, big.mark=",", nsmall = 0, digits=0,scientific = FALSE)}
nice.num2<-function(x){
  prettyNum(x, big.mark=",", nsmall = 2, digits=2,scientific = FALSE)}

# Models
get.models<-function(r.data,name){
  # will add models to list-----
  models<-list()
  
  
  ## overall models ------
  ## calendar
  ## 18-59 models ------
  ## 60-79 models ------
  ## 80 or above models ------
  ## female models ------
  ## male models ------
  
  ## overall models ------
  
  #data
  working.data<-r.data 
  dd<<-datadist(working.data); options(datadist = "dd" )
  
  #complete adjustment
  models[[paste0("m.",name, ".overall.linear", ".bmi.complete")]]<-cph(Surv(time, status) ~ bmi.all_time+  
                                                                         age+gender+ medea+smoke.all_time,
                                                                       surv=TRUE,x=TRUE,y=TRUE,
                                                                       data = working.data)
  models[[paste0("m.",name, ".overall.quadratic", ".bmi.complete")]]<-cph(Surv(time, status) ~ pol(bmi.all_time,2)+
                                                                            age+gender+ medea+smoke.all_time,
                                                                          surv=TRUE,x=TRUE,y=TRUE,
                                                                          data = working.data)
  models[[paste0("m.",name, ".overall.rcs3", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,3)+
                                                                       age+gender+ medea+smoke.all_time,
                                                                     surv=TRUE,x=TRUE,y=TRUE,
                                                                     data = working.data)
  models[[paste0("m.",name, ".overall.rcs4", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,4)+
                                                                       age+gender+ medea+smoke.all_time,
                                                                     surv=TRUE,x=TRUE,y=TRUE,
                                                                     data = working.data)
  models[[paste0("m.",name, ".overall.rcs5", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,5)+
                                                                       age+gender+ medea+smoke.all_time,
                                                                     surv=TRUE,x=TRUE,y=TRUE,
                                                                     data = working.data)
  
  ## models stratified by calendar month-- march ------
  
  #data
  working.data<-r.data
  dd<<-datadist(working.data); options(datadist = "dd" )
  working.data <- survSplit(Surv(time, status) ~ bmi.all_time + age + gender + medea + smoke.all_time,
                            working.data,
                            cut=c(31, 61), episode ="timegroup")
  working.data.march<-working.data %>% filter(timegroup==1)
  working.data.april<-working.data %>% filter(timegroup==2)
  
  
  
  #complete adjustment
  models[[paste0("m.",name, ".march.linear", ".bmi.complete")]]<-cph(Surv(time, status) ~ bmi.all_time+ 
                                                                       age+gender+ medea+smoke.all_time,
                                                                     surv=TRUE,x=TRUE,y=TRUE,
                                                                     data = working.data.march)
  models[[paste0("m.",name, ".march.quadratic", ".bmi.complete")]]<-cph(Surv(time, status) ~ pol(bmi.all_time,2)+
                                                                          age+gender+ medea+smoke.all_time,
                                                                        surv=TRUE,x=TRUE,y=TRUE,
                                                                        data = working.data.march)
  models[[paste0("m.",name, ".march.rcs3", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,3)+
                                                                     age+gender+ medea+smoke.all_time,
                                                                   surv=TRUE,x=TRUE,y=TRUE,
                                                                   data = working.data.march)
  models[[paste0("m.",name, ".march.rcs4", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,4)+
                                                                     age+gender+ medea+smoke.all_time,
                                                                   surv=TRUE,x=TRUE,y=TRUE,
                                                                   data = working.data.march)
  models[[paste0("m.",name, ".march.rcs5", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,5)+
                                                                     age+gender+ medea+smoke.all_time,
                                                                   surv=TRUE,x=TRUE,y=TRUE,
                                                                   data = working.data.march)
  
  ## models stratified by calendar month-- april ------
  
  #data
  
  #complete adjustment
  models[[paste0("m.",name, ".april.linear", ".bmi.complete")]]<-cph(Surv(time, status) ~ bmi.all_time+     
                                                                       age+gender+ medea+smoke.all_time,
                                                                     surv=TRUE,x=TRUE,y=TRUE,
                                                                     data = working.data.april)
  models[[paste0("m.",name, ".april.quadratic", ".bmi.complete")]]<-cph(Surv(time, status) ~ pol(bmi.all_time,2)+
                                                                          age+gender+ medea+smoke.all_time,
                                                                        surv=TRUE,x=TRUE,y=TRUE,
                                                                        data = working.data.april)
  models[[paste0("m.",name, ".april.rcs3", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,3)+
                                                                     age+gender+ medea+smoke.all_time,
                                                                   surv=TRUE,x=TRUE,y=TRUE,
                                                                   data = working.data.april)
  models[[paste0("m.",name, ".april.rcs4", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,4)+
                                                                     age+gender+ medea+smoke.all_time,
                                                                   surv=TRUE,x=TRUE,y=TRUE,
                                                                   data = working.data.april)
  models[[paste0("m.",name, ".april.rcs5", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,5)+
                                                                     age+gender+ medea+smoke.all_time,
                                                                   surv=TRUE,x=TRUE,y=TRUE,
                                                                   data = working.data.april)
  
  
  
  ## models for age 18-59  ------
  #data
  working.data<-r.data %>% filter(age_gr.b=="Aged 18 to 59")
  dd<<-datadist(working.data); options(datadist = "dd" )
  
  
  #complete adjustment
  models[[paste0("m.",name, ".firstage.linear", ".bmi.complete")]]<-cph(Surv(time, status) ~ bmi.all_time+  
                                                                          age+gender+ medea+smoke.all_time,
                                                                        surv=TRUE,x=TRUE,y=TRUE,
                                                                        data = working.data)
  models[[paste0("m.",name, ".firstage.quadratic", ".bmi.complete")]]<-cph(Surv(time, status) ~ pol(bmi.all_time,2)+
                                                                             age+gender+ medea+smoke.all_time,
                                                                           surv=TRUE,x=TRUE,y=TRUE,
                                                                           data = working.data)
  models[[paste0("m.",name, ".firstage.rcs3", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,3)+
                                                                        age+gender+ medea+smoke.all_time,
                                                                      surv=TRUE,x=TRUE,y=TRUE,
                                                                      data = working.data)
  models[[paste0("m.",name, ".firstage.rcs4", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,4)+
                                                                        age+gender+ medea+smoke.all_time,
                                                                      surv=TRUE,x=TRUE,y=TRUE,
                                                                      data = working.data)
  models[[paste0("m.",name, ".firstage.rcs5", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,5)+
                                                                        age+gender+ medea+smoke.all_time,
                                                                      surv=TRUE,x=TRUE,y=TRUE,
                                                                      data = working.data)
  
  ## models for age 60-79  ------
  #data
  working.data<-r.data %>% filter(age_gr.b=="Aged 60 to 79")
  dd<<-datadist(working.data); options(datadist = "dd" )
  
  
  #complete adjustment
  models[[paste0("m.",name, ".secondage.linear", ".bmi.complete")]]<-cph(Surv(time, status) ~ bmi.all_time+   
                                                                           age+gender+ medea+smoke.all_time,
                                                                         surv=TRUE,x=TRUE,y=TRUE,
                                                                         data = working.data)
  models[[paste0("m.",name, ".secondage.quadratic", ".bmi.complete")]]<-cph(Surv(time, status) ~ pol(bmi.all_time,2)+
                                                                              age+gender+ medea+smoke.all_time,
                                                                            surv=TRUE,x=TRUE,y=TRUE,
                                                                            data = working.data)
  models[[paste0("m.",name, ".secondage.rcs3", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,3)+
                                                                         age+gender+ medea+smoke.all_time,
                                                                       surv=TRUE,x=TRUE,y=TRUE,
                                                                       data = working.data)
  models[[paste0("m.",name, ".secondage.rcs4", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,4)+
                                                                         age+gender+ medea+smoke.all_time,
                                                                       surv=TRUE,x=TRUE,y=TRUE,
                                                                       data = working.data)
  models[[paste0("m.",name, ".secondage.rcs5", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,5)+
                                                                         age+gender+ medea+smoke.all_time,
                                                                       surv=TRUE,x=TRUE,y=TRUE,
                                                                       data = working.data)
  
  ## models for age 80 or above  ------
  #data
  working.data<-r.data %>% filter(age_gr.b=="Aged 80 or above")
  dd<<-datadist(working.data); options(datadist = "dd" )
  
  
  #complete adjustment
  models[[paste0("m.",name, ".thirdage.linear", ".bmi.complete")]]<-cph(Surv(time, status) ~ bmi.all_time+     
                                                                          age+gender+ medea+smoke.all_time,
                                                                        surv=TRUE,x=TRUE,y=TRUE,
                                                                        data = working.data)
  models[[paste0("m.",name, ".thirdage.quadratic", ".bmi.complete")]]<-cph(Surv(time, status) ~ pol(bmi.all_time,2)+
                                                                             age+gender+ medea+smoke.all_time,
                                                                           surv=TRUE,x=TRUE,y=TRUE,
                                                                           data = working.data)
  models[[paste0("m.",name, ".thirdage.rcs3", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,3)+
                                                                        age+gender+ medea+smoke.all_time,
                                                                      surv=TRUE,x=TRUE,y=TRUE,
                                                                      data = working.data)
  models[[paste0("m.",name, ".thirdage.rcs4", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,4)+
                                                                        age+gender+ medea+smoke.all_time,
                                                                      surv=TRUE,x=TRUE,y=TRUE,
                                                                      data = working.data)
  models[[paste0("m.",name, ".thirdage.rcs5", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,5)+
                                                                        age+gender+ medea+smoke.all_time,
                                                                      surv=TRUE,x=TRUE,y=TRUE,
                                                                      data = working.data)
  
  ## models for female ------
  #data
  working.data<-r.data %>% filter(gender=="Female")
  dd<<-datadist(working.data); options(datadist = "dd" )
  
  
  #complete adjustment
  models[[paste0("m.",name, ".female.linear", ".bmi.complete")]]<-cph(Surv(time, status) ~ bmi.all_time+    
                                                                        age+ medea+smoke.all_time,
                                                                      surv=TRUE,x=TRUE,y=TRUE,
                                                                      data = working.data)
  models[[paste0("m.",name, ".female.quadratic", ".bmi.complete")]]<-cph(Surv(time, status) ~ pol(bmi.all_time,2)+
                                                                           age+ medea+smoke.all_time,
                                                                         surv=TRUE,x=TRUE,y=TRUE,
                                                                         data = working.data)
  models[[paste0("m.",name, ".female.rcs3", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,3)+
                                                                      age+ medea+smoke.all_time,
                                                                    surv=TRUE,x=TRUE,y=TRUE,
                                                                    data = working.data)
  models[[paste0("m.",name, ".female.rcs4", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,4)+
                                                                      age+ medea+smoke.all_time,
                                                                    surv=TRUE,x=TRUE,y=TRUE,
                                                                    data = working.data)
  models[[paste0("m.",name, ".female.rcs5", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,5)+
                                                                      age+ medea+smoke.all_time,
                                                                    surv=TRUE,x=TRUE,y=TRUE,
                                                                    data = working.data)
  
  ## models for male ------
  #data
  working.data<-r.data %>% filter(gender=="Male")
  dd<<-datadist(working.data); options(datadist = "dd" )
  
  
  #complete adjustment
  models[[paste0("m.",name, ".male.linear", ".bmi.complete")]]<-cph(Surv(time, status) ~ bmi.all_time+  
                                                                      age+ medea+smoke.all_time,
                                                                    surv=TRUE,x=TRUE,y=TRUE,
                                                                    data = working.data)
  models[[paste0("m.",name, ".male.quadratic", ".bmi.complete")]]<-cph(Surv(time, status) ~ pol(bmi.all_time,2)+
                                                                         age+ medea+smoke.all_time,
                                                                       surv=TRUE,x=TRUE,y=TRUE,
                                                                       data = working.data)
  models[[paste0("m.",name, ".male.rcs3", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,3)+
                                                                    age+ medea+smoke.all_time,
                                                                  surv=TRUE,x=TRUE,y=TRUE,
                                                                  data = working.data)
  models[[paste0("m.",name, ".male.rcs4", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,4)+
                                                                    age+ medea+smoke.all_time,
                                                                  surv=TRUE,x=TRUE,y=TRUE,
                                                                  data = working.data)
  models[[paste0("m.",name, ".male.rcs5", ".bmi.complete")]]<-cph(Surv(time, status) ~ rcs(bmi.all_time,5)+
                                                                    age+ medea+smoke.all_time,
                                                                  surv=TRUE,x=TRUE,y=TRUE,
                                                                  data = working.data)
  
  ## output ----
  models
}


# To get relative hazards for each model in list
# also add in AIC and BIC
get.r.hazard<-function(models,   #list of models
                       bmi.1,    # reference bmi 
                       bmi.2){   # comparison bmi
  
  
  output<-lapply(models, function(x) {
    model<- x
    output<-NULL
    for(i in 1:length(bmi.2)){  
      
      working.summary<-head(as.data.frame(summary({{model}}, 
                                                  bmi.all_time=c({{bmi.1}},{{bmi.2[i]}}), antilog=FALSE)),1)  # 1st- bmi
      working.summary<-working.summary %>% 
        select(Effect,`Lower 0.95`, `Upper 0.95`) %>% 
        mutate(hr=exp(Effect),
               hr.low=exp(`Lower 0.95`),
               hr.high=exp(`Upper 0.95`)) %>% 
        mutate(ref.bmi.all_time=bmi.1,
               rel.bmi.all_time=bmi.2[i]) %>% 
        select(hr, hr.low, hr.high, ref.bmi.all_time, rel.bmi.all_time)
      #browser()
      working.summary$aic<-AIC({{model}})
      working.summary$bic<-BIC({{model}})
      
      output<-rbind(output, working.summary)
      
    }
    
    output
    
  })
  # to dataframe
  output <-bind_rows(output, .id = "model")
  output
}


```

```{r, cache=TRUE}
# get models -----
models.healthy.diagnosis<-get.models(r.healthy.diagnosis, "healthy.diagnosis")
```

# Transition 1: From general population to diagnosed with COVID-19 
```{r}
# models and relative hazards from models -----
r.hazard<-get.r.hazard(model=models.healthy.diagnosis,
                       bmi.1=22,
                       bmi.2=seq(15,60, 1)) 

```

## Comparison of alternative models
### Model fit
```{r}
fit<-rbind(
  
  #overall - complete
  r.hazard %>% 
    filter(str_detect(model, ".overall")) %>% 
    filter(str_detect(model, ".bmi.complete")) %>% 
    select(model, aic, bic) %>% 
    distinct() %>% 
    mutate(bic=nice.num(bic)) %>% 
    mutate(aic=nice.num(aic)) %>% 
    mutate(type=str_extract(model, paste(c("linear", "quadratic", "rcs3", "rcs4", "rcs5"), collapse="|"))) %>% 
    select(type, aic, bic) %>% 
    mutate(name="overall.bmi.complete"),  
  
  
  #march - complete
  r.hazard %>%
    filter(str_detect(model, ".march")) %>%
    filter(str_detect(model, ".bmi.complete")) %>%
    select(model, aic, bic) %>%
    distinct() %>%
    mutate(bic=nice.num(bic)) %>%
    mutate(aic=nice.num(aic)) %>%
    mutate(type=str_extract(model, paste(c("linear", "quadratic", "rcs3", "rcs4", "rcs5"), collapse="|"))) %>%
    select(type, aic, bic) %>%
    mutate(name="march.bmi.complete"),
  
  #april - complete
  r.hazard %>%
    filter(str_detect(model, ".april")) %>%
    filter(str_detect(model, ".bmi.complete")) %>%
    select(model, aic, bic) %>%
    distinct() %>%
    mutate(bic=nice.num(bic)) %>%
    mutate(aic=nice.num(aic)) %>%
    mutate(type=str_extract(model, paste(c("linear", "quadratic", "rcs3", "rcs4", "rcs5"), collapse="|"))) %>%
    select(type, aic, bic) %>%
    mutate(name="april.bmi.complete"),
  
  #1 - complete
  r.hazard %>% 
    filter(str_detect(model, ".firstage")) %>% 
    filter(str_detect(model, ".bmi.complete")) %>% 
    select(model, aic, bic) %>% 
    distinct() %>% 
    mutate(bic=nice.num(bic)) %>% 
    mutate(aic=nice.num(aic)) %>% 
    mutate(type=str_extract(model, paste(c("linear", "quadratic", "rcs3", "rcs4", "rcs5"), collapse="|"))) %>% 
    select(type, aic, bic) %>% 
    mutate(name="firstage.bmi.complete"), 
  
  
  #2 - complete
  r.hazard %>% 
    filter(str_detect(model, ".secondage")) %>% 
    filter(str_detect(model, ".bmi.complete")) %>% 
    select(model, aic, bic) %>% 
    distinct() %>% 
    mutate(bic=nice.num(bic)) %>% 
    mutate(aic=nice.num(aic)) %>% 
    mutate(type=str_extract(model, paste(c("linear", "quadratic", "rcs3", "rcs4", "rcs5"), collapse="|"))) %>% 
    select(type, aic, bic) %>% 
    mutate(name="secondage.bmi.complete"), 
  
  
  
  #3 - complete
  r.hazard %>% 
    filter(str_detect(model, ".thirdage")) %>% 
    filter(str_detect(model, ".bmi.complete")) %>% 
    select(model, aic, bic) %>% 
    distinct() %>% 
    mutate(bic=nice.num(bic)) %>% 
    mutate(aic=nice.num(aic)) %>% 
    mutate(type=str_extract(model, paste(c("linear", "quadratic", "rcs3", "rcs4", "rcs5"), collapse="|"))) %>% 
    select(type, aic, bic) %>% 
    mutate(name="thirdage.bmi.complete"), 
  
  # female
  
  
  #3 - complete
  r.hazard %>% 
    filter(str_detect(model, ".female")) %>% 
    filter(str_detect(model, ".bmi.complete")) %>% 
    select(model, aic, bic) %>% 
    distinct() %>% 
    mutate(bic=nice.num(bic)) %>% 
    mutate(aic=nice.num(aic)) %>% 
    mutate(type=str_extract(model, paste(c("linear", "quadratic", "rcs3", "rcs4", "rcs5"), collapse="|"))) %>% 
    select(type, aic, bic) %>% 
    mutate(name="female.bmi.complete"), 
  
  
  # male
  
  #3 - complete
  r.hazard %>% 
    filter(str_detect(model, ".male")) %>% 
    filter(!str_detect(model, ".female")) %>% 
    filter(str_detect(model, ".bmi.complete")) %>% 
    select(model, aic, bic) %>% 
    distinct() %>% 
    mutate(bic=nice.num(bic)) %>% 
    mutate(aic=nice.num(aic)) %>% 
    mutate(type=str_extract(model, paste(c("linear", "quadratic", "rcs3", "rcs4", "rcs5"), collapse="|"))) %>% 
    select(type, aic, bic) %>% 
    mutate(name="male.bmi.complete"))


fit<-fit %>%
  pivot_wider(names_from = name, 
              values_from = c(aic,bic)) 
fit<-fit %>%
  select(type ,       
         
         aic_overall.bmi.complete, bic_overall.bmi.complete,
         
         aic_march.bmi.complete, bic_march.bmi.complete,
         
         aic_april.bmi.complete, bic_april.bmi.complete,
         
         aic_firstage.bmi.complete, bic_firstage.bmi.complete,
         
         aic_secondage.bmi.complete, bic_secondage.bmi.complete,
         
         aic_thirdage.bmi.complete, bic_thirdage.bmi.complete,
         
         aic_female.bmi.complete, bic_female.bmi.complete,
         
         aic_male.bmi.complete, bic_male.bmi.complete
         
         
  )


kable(fit %>% 
        mutate(type=ifelse(type=="rcs3",
                           "restricted cubic spline (3 knots)",
                           ifelse(type=="rcs4",
                                  "restricted cubic spline (4 knots)",
                                  ifelse(type=="rcs5",
                                         "restricted cubic spline (5 knots)",      
                                         type)))), 
      col.names = c("Type",  
                    "AIC","BIC", 
                    "AIC","BIC",
                    "AIC","BIC",
                    "AIC","BIC", 
                    "AIC","BIC", 
                    "AIC","BIC",
                    "AIC","BIC", 
                    "AIC","BIC"))  %>%
  kable_styling(bootstrap_options = c("striped", "bordered"))  %>%
  add_header_above( c("",
                      "Complete adjustment" = 2, 
                      "Complete adjustment" = 2,
                      "Complete adjustment" = 2,
                      "Complete adjustment" = 2, 
                      "Complete adjustment" = 2,
                      "Complete adjustment" = 2, 
                      "Complete adjustment" = 2,
                      "Complete adjustment" = 2
                      
  ))  %>%
  add_header_above( c("",
                      "Overall" = 2,
                      "March"=2,
                      "April"=2,
                      "Aged 18 to 59" = 2,
                      "Aged 60 to 79" = 2,
                      "Aged 80 or above"=2,
                      "Female" = 2,
                      "Male" = 2))%>%
  add_header_above(
    c("From general population to diagnosed with COVID-19" = 17))
```
